services:
  bibfiles:
    build: .
    image: bibfiles:latest
    container_name: bibfiles
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - bibfiles-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: bibfiles_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bibfiles
      MYSQL_USER: bibfiles
      MYSQL_PASSWORD: bibfiles
      MYSQL_ROOT_PASSWORD: bibfiles
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - bibfiles-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bibfiles_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: bibfiles
    networks:
      - bibfiles-network
      
  selenium:
    image: selenium/standalone-chrome
    container_name: bibfiles_selenium
    ports:
      - "7900:7900"
    networks:
      - bibfiles-network
    shm_size: 2gb

  # No /etc/hosts do seu computador colocar a linha `127.0.0.1 auth.local` 
  # particularidades do protocolo oAuth1 usado na USP
  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: bibfiles_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      bibfiles-network:
        aliases:
          - auth.local

  mailpit:
    image: axllent/mailpit:latest
    container_name: bibfiles_mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface Web
    networks:
      - bibfiles-network

networks:
  bibfiles-network:

volumes:
  mariadb_data: